[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_USE_REALTIME = "true"
  VITE_DEBUG_MODE = "true"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  framework = "#auto"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 